import './placeLogics.dart';
import 'package:get/get.dart';

//states & UTs
List stateOptions = [
  stateModal('AN'.tr, 'Andaman Nicobar Islands'.tr, false),
  stateModal('AP'.tr, 'Andhra Pradesh'.tr, true),
  stateModal('AR'.tr, 'Arunachal Pradesh'.tr, true),
  stateModal('AS'.tr, 'Assam'.tr, true),
  stateModal('BR'.tr, 'Bihar'.tr, true),
  stateModal('CH'.tr, 'Chandigarh'.tr, false),
  stateModal('CG'.tr, 'Chattisgarh'.tr, true),
  stateModal('DD'.tr, 'Dadra and Nagar Haveli & Daman and Diu'.tr, false),
  stateModal('DL'.tr, 'Delhi'.tr, false),
  stateModal('GA'.tr, 'Goa'.tr, true),
  stateModal('GJ'.tr, 'Gujarat'.tr, true),
  stateModal('HR'.tr, 'Haryana'.tr, true),
  stateModal('HP'.tr, 'Himachal Pradesh'.tr, true),
  stateModal('JK'.tr, 'Jammu & Kashmir'.tr, false),
  stateModal('JH'.tr, 'Jharkhand'.tr, true),
  stateModal('KA'.tr, 'Karnataka'.tr, true),
  stateModal('KL'.tr, 'Kerala'.tr, true),
  stateModal('LA'.tr, 'Ladakh'.tr, false),
  stateModal('MP'.tr, 'Madhya Pradesh'.tr, true),
  stateModal('MH'.tr, 'Maharashtra'.tr, true),
  stateModal('MN'.tr, 'Manipur'.tr, true),
  stateModal('ML'.tr, 'Meghalaya'.tr, true),
  stateModal('MZ'.tr, 'Mizoram'.tr, true),
  stateModal('NL'.tr, 'Nagaland'.tr, true),
  stateModal('OD'.tr, 'Odisha'.tr, true),
  stateModal('PY'.tr, 'Puducherry'.tr, false),
  stateModal('PB'.tr, 'Punjab'.tr, true),
  stateModal('RJ'.tr, 'Rajasthan'.tr, true),
  stateModal('SK'.tr, 'Sikkim'.tr, true),
  stateModal('TN'.tr, 'Tamil Nadu'.tr, true),
  stateModal('TS'.tr, 'Telangana'.tr, true),
  stateModal('TR'.tr, 'Tripura'.tr, true),
  stateModal('UP'.tr, 'Uttar Pradesh'.tr, true),
  stateModal('UK'.tr, 'Uttarakhand'.tr, true),
  stateModal('WB'.tr, 'West Bengal'.tr, true),
];

//CITIES
//
//andaman & nicobar islands
List anCities = [
  cityModal('Port Blair'.tr, 'AN-01'),
];

//arunachal pradesh
List apCities = [
  cityModal('Anantapur'.tr, 'AP-02'),
  cityModal('Chittoor'.tr, 'AP-03'),
  cityModal('Eluru'.tr, 'AP-37'),
  cityModal('Gajuwaka'.tr, 'AP-33'),
  cityModal('Guntur'.tr, 'AP-07'),
  cityModal('Kadapa'.tr, 'AP-04'),
  cityModal('Kakinada'.tr, 'AP-05'),
  cityModal('Kurnool'.tr, 'AP-21'),
  cityModal('Machilipatnam'.tr, 'APXX1'),
  cityModal('Narsipatnam'.tr, 'AP-34'),
  cityModal('Nellore'.tr, 'AP-26'),
  cityModal('Ongole'.tr, 'AP-27'),
  cityModal('Srikakulam'.tr, 'AP-30'),
  cityModal('Vijayawada'.tr, 'AP-16'),
  cityModal('Visakhapatnam'.tr, 'AP-31'),
  cityModal('Vizag'.tr, 'APXX2'),
  cityModal('Vizianagaram'.tr, 'AP-35'),
];

//andhra pradesh
List arCities = [
  cityModal('Along'.tr, 'AR-08'),
  cityModal('Anini'.tr, 'ARXX1'),
  cityModal('Basar'.tr, 'ARXX2'),
  cityModal('Bomdila'.tr, 'AR-04'),
  cityModal('Changlang'.tr, 'AR-12'),
  cityModal('Daporijo'.tr, 'AR-07'),
  cityModal('Hawai'.tr, 'AR-17'),
  cityModal('Itanagar'.tr, 'AR-01'),
  cityModal('Jamin'.tr, 'ARXX3'),
  cityModal('Khonsa'.tr, 'AR-13'),
  cityModal('Koloriang'.tr, 'ARXX4'),
  cityModal('Lemmi'.tr, 'ARXX5'),
  cityModal('Likabali'.tr, 'ARXX6'),
  cityModal('Longding'.tr, 'ARXX7'),
  cityModal('Namsai'.tr, 'AR-20'),
  cityModal('Pangin'.tr, 'ARXX8'),
  cityModal('Pasighat'.tr, 'ARXX9'),
  cityModal('Raga'.tr, 'ARXX10'),
  cityModal('Roing'.tr, 'AR-16'),
  cityModal('Seppa'.tr, 'AR-05'),
  cityModal('Tato'.tr, 'ARXX11'),
  cityModal('Tawang'.tr, 'AR-03'),
  cityModal('Tezu'.tr, 'AR-11'),
  cityModal('Yingkiong'.tr, 'ARXX12'),
  cityModal('Ziro'.tr, 'ARXX13'),
];

//assam
List asCities = [
  cityModal('Amingaon'.tr, 'ASXX1'),
  cityModal('Barpeta'.tr, 'AS-15'),
  cityModal('Bishwanath'.tr, 'AS-32'),
  cityModal('Bongaigaon'.tr, 'AS-19'),
  cityModal('Charaideo'.tr, 'AS-33'),
  cityModal('Darrang'.tr, 'AS-13'),
  cityModal('Dhemaji'.tr, 'AS-22'),
  cityModal('Dhubri'.tr, 'AS-17'),
  cityModal('Dibrugarh'.tr, 'AS-06'),
  cityModal('Diphu'.tr, 'ASXX2'),
  cityModal('Garamur'.tr, 'ASXX3'),
  cityModal('Goalpara'.tr, 'AS-18'),
  cityModal('Golaghat'.tr, 'AS-05'),
  cityModal('Guwahati'.tr, 'AS-01'),
  cityModal('Haflong'.tr, 'ASXX4'),
  cityModal('Hailakandi'.tr, 'AS-21'),
  cityModal('Hamren'.tr, 'ASXX5'),
  cityModal('Hatsingimari'.tr, 'AS-34'),
  cityModal('Hojai'.tr, 'AS-31'),
  cityModal('Jorhat'.tr, 'AS-03'),
  cityModal('Kajalgaon'.tr, 'ASXX6'),
  cityModal('Karbi Anglong'.tr, 'AS-09'),
  cityModal('Karimganj'.tr, 'AS-10'),
  cityModal('Kokrajhar'.tr, 'AS-16'),
  cityModal('Majuli'.tr, 'AS-29'),
  cityModal('Mangaldoi'.tr, 'ASXX7'),
  cityModal('Morigaon'.tr, 'ASXX8'),
  cityModal('Mushalpur'.tr, 'ASXX9'),
  cityModal('Nagaon'.tr, 'AS-02'),
  cityModal('Nalbari'.tr, 'AS-14'),
  cityModal('North Lakhimpur'.tr, 'ASXX10'),
  cityModal('Silchar'.tr, 'AS-11'),
  cityModal('Sivasagar'.tr, 'AS-04'),
  cityModal('Sonari'.tr, 'ASXX11'),
  cityModal('Tezpur'.tr, 'ASXX12'),
  cityModal('Tinsukia'.tr, 'AS-23'),
  cityModal('Udalguri'.tr, 'ASXX13'),
];

//bihar
List brCities = [
  cityModal('Araria'.tr, 'BR-38'),
  cityModal('Arrah'.tr, 'BR-03'),
  cityModal('Arwal'.tr, 'BR-56'),
  cityModal('Aurangabad'.tr, 'BR-26'),
  cityModal('Banka'.tr, 'BR-51'),
  cityModal('Begusarai'.tr, 'BR-09'),
  cityModal('Bettiah'.tr, 'BR-22'),
  cityModal('Bhabua'.tr, 'BR-45'),
  cityModal('Bhagalpur'.tr, 'BR-10'),
  cityModal('Bihar Sharif'.tr, 'BR-21'),
  cityModal('Buxar'.tr, 'BR-44'),
  cityModal('Chhapra'.tr, 'BRXX1'),
  cityModal('Darbhanga'.tr, 'BR-07'),
  cityModal('Dehri'.tr, 'BR-24'),
  cityModal('Gaya'.tr, 'BR-02'),
  cityModal('Gopalganj'.tr, 'BR-28'),
  cityModal('Hajipur'.tr, 'BR-31'),
  cityModal('Jamui'.tr, 'BR-46'),
  cityModal('Jehanabad'.tr, 'BR-25'),
  cityModal('Katihar'.tr, 'BR-39'),
  cityModal('Khagaria'.tr, 'BR-34'),
  cityModal('Kishanganj'.tr, 'BR-37'),
  cityModal('Lakhisarai'.tr, 'BRXX2'),
  cityModal('Madhepura'.tr, 'BR-43'),
  cityModal('Madhubani'.tr, 'BR-32'),
  cityModal('Motihari'.tr, 'BR-05'),
  cityModal('Munger'.tr, 'BR-08'),
  cityModal('Muzaffarpur'.tr, 'BR-06'),
  cityModal('Nawada'.tr, 'BR-27'),
  cityModal('Patna'.tr, 'BR-01'),
  cityModal('Purnia'.tr, 'BR-11'),
  cityModal('Saharsa'.tr, 'BR-19'),
  cityModal('Samastipur'.tr, 'BR-33'),
  cityModal('Sasaram'.tr, 'BR-57'),
  cityModal('Sheikhpura'.tr, 'BR-52'),
  cityModal('Sheohar'.tr, 'BR-55'),
  cityModal('Sitamarhi'.tr, 'BR-30'),
  cityModal('Siwan'.tr, 'BR-29'),
  cityModal('Supaul'.tr, 'BR-50'),
];

//chattisgarh
List cgCities = [
  cityModal('Ambikapur'.tr, 'CG-15'),
  cityModal('Baikunthpur'.tr, 'CG-16'),
  cityModal('Balod'.tr, 'CG-24'),
  cityModal('Baloda Bazar'.tr, 'CG-22'),
  cityModal('Bemetara'.tr, 'CG-25'),
  cityModal('Bijapur'.tr, 'CG-20'),
  cityModal('Bilaspur'.tr, 'CG-10'),
  cityModal('Dantewada'.tr, 'CG-18'),
  cityModal('Dhamtari'.tr, 'CG-05'),
  cityModal('Durg'.tr, 'CG-07'),
  cityModal('Gariaband'.tr, 'CG-23'),
  cityModal('Jagdalpur'.tr, 'CG-17'),
  cityModal('Janjgir'.tr, 'CG-11'),
  cityModal('Jashpur Nagar'.tr, 'CG-14'),
  cityModal('Kanker'.tr, 'CG-19'),
  cityModal('Kawardha'.tr, 'CG-09'),
  cityModal('Kondagaon'.tr, 'CG-27'),
  cityModal('Korba'.tr, 'CG-12'),
  cityModal('Mahasamund'.tr, 'CG-06'),
  cityModal('Mungeli'.tr, 'CG-28'),
  cityModal('Naila Janjgir'.tr, 'CGXX1'),
  cityModal('Narayanpur'.tr, 'CGXX2'),
  cityModal('Raigarh'.tr, 'CG-13'),
  cityModal('Raipur'.tr, 'CG-04'),
  cityModal('Rajnandgaon'.tr, 'CG-08'),
  cityModal('Sukma'.tr, 'CG-26'),
  cityModal('Surajpur'.tr, 'CG-29'),
];

//chandigarh
List chCities = [
  cityModal('Sector 43'.tr, 'CHXX1'),
  cityModal('Sector 17'.tr, 'CHXX2'),
  cityModal('Sector 22'.tr, 'CHXX3'),
  cityModal('Sector 34'.tr, 'CHXX4'),
  cityModal('Sector 36'.tr, 'CHXX5'),
  cityModal('Sector 37'.tr, 'CHXX6'),
  cityModal('Sector 15'.tr, 'CHXX7'),
  cityModal('Industrial Area Phase 1'.tr, 'CHXX8'),
  cityModal('Industrial Area Phase 2'.tr, 'CHXX9'),
];

//dadra nagar and haveli & daman and diu
List ddCities = [
  cityModal('Daman'.tr, 'DD-02'),
  cityModal('Diu'.tr, 'DD-03'),
  cityModal('Silvassa'.tr, 'DD-01'),
];

//delhi
List dlCities = [
  cityModal('Civil Lines'.tr, 'DL-01'),
  cityModal('Dwarka'.tr, 'DL-09'),
  cityModal('Indraprastha Depot'.tr, 'DL-02'),
  cityModal('Janakpuri'.tr, 'DL-04'),
  cityModal('Loni Road'.tr, 'DL-05'),
  cityModal('Mayur Vihar'.tr, 'DL-07'),
  cityModal('Raja Garden'.tr, 'DL-10'),
  cityModal('Rohini'.tr, 'DL-11'),
  cityModal('Sarai Kale Khan'.tr, 'DL-06'),
  cityModal('Sheikh Sarai'.tr, 'DL-03'),
  cityModal('Surajmal Vihar'.tr, 'DL-13'),
  cityModal('Vasant Vihar'.tr, 'DL-12'),
  cityModal('Wazir Pur'.tr, 'DL-08'),
];

//goa
List gaCities = [
  cityModal('Bicholim'.tr, 'GA-04'),
  cityModal('Dharbandora'.tr, 'GA-12'),
  cityModal('Mapusa'.tr, 'GA-03'),
  cityModal('Margao'.tr, 'GA-08'),
  cityModal('Panajim'.tr, 'GA-07'),
  cityModal('Pernem'.tr, 'GA-11'),
  cityModal('Ponda'.tr, 'GA-05'),
  cityModal('Quepem'.tr, 'GA-09'),
  cityModal('Vasco da Gama'.tr, 'GA-06'),
];

//gujarat
List gjCities = [
  cityModal('Ahmedabad'.tr, 'GJ-01'),
  cityModal('Ahwa'.tr, 'GJXX1'),
  cityModal('Amreli'.tr, 'GJ-14'),
  cityModal('Anand'.tr, 'GJ-23'),
  cityModal('Bardoli'.tr, 'GJ-19'),
  cityModal('Bavla'.tr, 'GJ-38'),
  cityModal('Bharuch'.tr, 'GJ-16'),
  cityModal('Bhavnagar'.tr, 'GJ-04'),
  cityModal('Bhuj'.tr, 'GJ-12'),
  cityModal('Botad'.tr, 'GJ-33'),
  cityModal('Chhota Udepur'.tr, 'GJ-34'),
  cityModal('Dahod'.tr, 'GJ-20'),
  cityModal('Gandhinagar'.tr, 'GJ-18'),
  cityModal('Godhra'.tr, 'GJ-17'),
  cityModal('Himmatnagar'.tr, 'GJ-09'),
  cityModal('Jamnagar'.tr, 'GJ-10'),
  cityModal('Junagadh'.tr, 'GJ-11'),
  cityModal('Khambhaliya'.tr, 'GJ-37'),
  cityModal('Lunawada'.tr, 'GJ-35'),
  cityModal('Mehsana'.tr, 'GJ-02'),
  cityModal('Modasa'.tr, 'GJ-31'),
  cityModal('Morbi'.tr, 'GJ-36'),
  cityModal('Nadiad'.tr, 'GJ-07'),
  cityModal('Navsari'.tr, 'GJ-21'),
  cityModal('Pal'.tr, 'GJ-28'),
  cityModal('Palanpur'.tr, 'GJ-08'),
  cityModal('Patan'.tr, 'GJ-24'),
  cityModal('Porbandar'.tr, 'GJ-25'),
  cityModal('Rajkot'.tr, 'GJ-03'),
  cityModal('Rajpipla'.tr, 'GJ-22'),
  cityModal('Surat'.tr, 'GJ-05'),
  cityModal('Surendranagar'.tr, 'GJ-13'),
  cityModal('Vadodara'.tr, 'GJ-06'),
  cityModal('Valsad'.tr, 'GJ-15'),
  cityModal('Veraval'.tr, 'GJ-32'),
  cityModal('Vyara'.tr, 'GJ-26'),
];

//himachal pradesh
List hpCities = [
  cityModal('Amb'.tr, 'HP-19'),
  cityModal('Arki'.tr, 'HP-11'),
  cityModal('Baijnath'.tr, 'HP-53'),
  cityModal('Barsar'.tr, 'HP-21'),
  cityModal('Bilaspur'.tr, 'HP-24'),
  cityModal('Chamba'.tr, 'HP-44'),
  cityModal('Chopal'.tr, 'HP-08'),
  cityModal('Chowari'.tr, 'HP-57'),
  cityModal('Dalhousie'.tr, 'HP-47'),
  cityModal('Dharamshala'.tr, 'HP-39'),
  cityModal('Gagret'.tr, 'HP-19AA'),
  cityModal('Ghumarwin'.tr, 'HP-23'),
  cityModal('Hamirpur'.tr, 'HP-22'),
  cityModal('Jaisinghpur'.tr, 'HP-56'),
  cityModal('Jawali'.tr, 'HP-54'),
  cityModal('Kandaghat'.tr, 'HP-13'),
  cityModal('Kangra'.tr, 'HP-04'),
  cityModal('Kaza'.tr, 'HP-41'),
  cityModal('Keylong'.tr, 'HP-42'),
  cityModal('Kullu'.tr, 'HP-34'),
  cityModal('Manali'.tr, 'HP-58'),
  cityModal('Mandi'.tr, 'HP-05'),
  cityModal('Nadaun'.tr, 'HP-55'),
  cityModal('Nahan'.tr, 'HP-18'),
  cityModal('Nalagarh'.tr, 'HP-12'),
  cityModal('Nichar'.tr, 'HP-26'),
  cityModal('Nurpur'.tr, 'HP-38'),
  cityModal('Palampur'.tr, 'HP-37'),
  cityModal('Paonta Sahib'.tr, 'HP-17'),
  cityModal('Parwanoo'.tr, 'HP-15'),
  cityModal('Reckong Peo'.tr, 'HP-25'),
  cityModal('Rohru'.tr, 'HP-10'),
  cityModal('Shimla'.tr, 'HP-03'),
  cityModal('Solan'.tr, 'HP-14'),
  cityModal('Theog'.tr, 'HP-09'),
  cityModal('Una'.tr, 'HP-20'),
];

//haryana
List hrCities = [
  cityModal('Ambala'.tr, 'HR-01'),
  cityModal('Bahadurgarh'.tr, 'HR-13'),
  cityModal('Ballabgarh'.tr, 'HR-29'),
  cityModal('Bhiwani'.tr, 'HR-16'),
  cityModal('Charkhi Dadri'.tr, 'HR-19'),
  cityModal('Ellenabad'.tr, 'HR-44'),
  cityModal('Faridabad'.tr, 'HR-38'),
  cityModal('Fatehabad'.tr, 'HR-22'),
  cityModal('Ferozepur Jhirka'.tr, 'HR-28'),
  cityModal('Ganaur'.tr, 'HR-42'),
  cityModal('Gohana'.tr, 'HR-11'),
  cityModal('Guhla'.tr, 'HR-09'),
  cityModal('Gurugram'.tr, 'HR-26'),
  cityModal('Hansi'.tr, 'HR-21'),
  cityModal('Hisar'.tr, 'HR-20'),
  cityModal('Jagadhri'.tr, 'HR-02'),
  cityModal('Jhajjar'.tr, 'HR-14'),
  cityModal('Jind'.tr, 'HR-31'),
  cityModal('Kaithal'.tr, 'HR-08'),
  cityModal('Kalka'.tr, 'HR-49'),
  cityModal('Karnal'.tr, 'HR-05'),
  cityModal('Kosli'.tr, 'HR-43'),
  cityModal('Kurukshetra'.tr, 'HRXX1'),
  cityModal('Mahendragarh'.tr, 'HR-34'),
  cityModal('Mandi Dabwali'.tr, 'HR-25'),
  cityModal('Naraingarh'.tr, 'HR-04'),
  cityModal('Narnaul'.tr, 'HR-35'),
  cityModal('Nuh'.tr, 'HR-27'),
  cityModal('Palwal'.tr, 'HR-30'),
  cityModal('Panchkula'.tr, 'HR-03'),
  cityModal('Panipat'.tr, 'HR-06'),
  cityModal('Pehowa'.tr, 'HR-41'),
  cityModal('Ratia'.tr, 'HR-59'),
  cityModal('Rewari'.tr, 'HR-36'),
  cityModal('Rohtak'.tr, 'HR-12'),
  cityModal('Safidon'.tr, 'HR-33'),
  cityModal('Sirsa'.tr, 'HR-24'),
  cityModal('Siwani'.tr, 'HR-17'),
  cityModal('Sonipat'.tr, 'HR-10'),
  cityModal('Thanesar'.tr, 'HR-07'),
  cityModal('Tohana'.tr, 'HR-23'),
  cityModal('Yamunanagar'.tr, 'HR-58'),
];

//jharkhand
List jhCities = [
  cityModal('Bokaro'.tr, 'JH-09'),
  cityModal('Chaibasa'.tr, 'JH-06'),
  cityModal('Chatra'.tr, 'JH-13'),
  cityModal('Daltonganj'.tr, 'JH-03'),
  cityModal('Deoghar'.tr, 'JH-15'),
  cityModal('Dhanbad'.tr, 'JH-10'),
  cityModal('Dumka'.tr, 'JH-04'),
  cityModal('Garhwa'.tr, 'JH-14'),
  cityModal('Giridih'.tr, 'JH-11'),
  cityModal('Godda'.tr, 'JH-17'),
  cityModal('Gumla'.tr, 'JH-07'),
  cityModal('Jamshedpur'.tr, 'JH-05'),
  cityModal('Jamtara'.tr, 'JH-21'),
  cityModal('Khunti'.tr, 'JH-23'),
  cityModal('Koderma'.tr, 'JH-12'),
  cityModal('Latehar'.tr, 'JH-19'),
  cityModal('Lohardaga'.tr, 'JH-08'),
  cityModal('Pakur'.tr, 'JH-16'),
  cityModal('Ramgarh'.tr, 'JH-02'),
  cityModal('Ranchi'.tr, 'JH-01'),
  cityModal('Sahibganj'.tr, 'JH-18'),
  cityModal('Seraikela'.tr, 'JH-22'),
  cityModal('Simdega'.tr, 'JH-20'),
];

//jammu & kashmir
List jkCities = [
  cityModal('Anantnag'.tr, 'JK-03'),
  cityModal('Badgam'.tr, 'JKXX1'),
  cityModal('Bandipore'.tr, 'JKXX2'),
  cityModal('Baramulla'.tr, 'JKXX3'),
  cityModal('Doda'.tr, 'JK-06'),
  cityModal('Ganderbal'.tr, 'JK-16'),
  cityModal('Jammu'.tr, 'JK-02'),
  cityModal('Kathua'.tr, 'JKXX4'),
  cityModal('Kishtwar'.tr, 'JK-17'),
  cityModal('Kulgam'.tr, 'JKXX5'),
  cityModal('Kupwara'.tr, 'JKXX6'),
  cityModal('Lakhanpur'.tr, 'JK-08'),
  cityModal('Poonch'.tr, 'JKXX7'),
  cityModal('Pulwama'.tr, 'JK-13'),
  cityModal('Rajouri'.tr, 'JK-11'),
  cityModal('Ramban'.tr, 'JK-19'),
  cityModal('Reasi'.tr, 'JK-20'),
  cityModal('Samba'.tr, 'JK-21'),
  cityModal('Shopian'.tr, 'JK-22'),
  cityModal('Srinagar'.tr, 'JK-01'),
  cityModal('Udhampur'.tr, 'JK-14'),
];

//karnataka
List kaCities = [
  cityModal('Athani'.tr, 'KA-71'),
  cityModal('Bagalkote'.tr, 'KA-29'),
  cityModal('Bailhongal'.tr, 'KA-24'),
  cityModal('Ballari'.tr, 'KA-34'),
  cityModal('Banashankari'.tr, 'KA-58'),
  cityModal('Bantwal'.tr, 'KA-70'),
  cityModal('Basavakalyan'.tr, 'KA-56'),
  cityModal('Belagavi'.tr, 'KA-22'),
  cityModal('Bengaluru'.tr, 'KA-01'),
  cityModal('Bhalki'.tr, 'KA-39'),
  cityModal('Bidar'.tr, 'KA-38'),
  cityModal('Chamarajanagara'.tr, 'KA-10'),
  cityModal('Chandapura'.tr, 'KA-59'),
  cityModal('Chikkaballapura'.tr, 'KA-40'),
  cityModal('Chikkamagaluru'.tr, 'KA-18'),
  cityModal('Chikkodi'.tr, 'KA-23'),
  cityModal('Chintamani'.tr, 'KA-67'),
  cityModal('Chitradurga'.tr, 'KA-16'),
  cityModal('Dandeli'.tr, 'KA-65'),
  cityModal('Davanagere'.tr, 'KA-17'),
  cityModal('Devanahalli'.tr, 'KA-43'),
  cityModal('Dharwad'.tr, 'KA-25'),
  cityModal('Electronic City'.tr, 'KA-51'),
  cityModal('Gadag'.tr, 'KA-26'),
  cityModal('Gokak'.tr, 'KA-49'),
  cityModal('Hassan'.tr, 'KA-13'),
  cityModal('Haveri'.tr, 'KA-27'),
  cityModal('Honnavar'.tr, 'KA-47'),
  cityModal('Hosapete'.tr, 'KA-35'),
  cityModal('Hunsur'.tr, 'KA-45'),
  cityModal('Jamkhandi'.tr, 'KA-48'),
  cityModal('Jnana Bharathi'.tr, 'KA-41'),
  cityModal('Kalaburagi'.tr, 'KA-32'),
  cityModal('Karwar'.tr, 'KA-30'),
  cityModal('Kolar'.tr, 'KA-07'),
  cityModal('Koppal'.tr, 'KA-37'),
  cityModal('Krishnarajapura'.tr, 'KA-53'),
  cityModal('Madhugiri'.tr, 'KA-64'),
  cityModal('Madikeri'.tr, 'KA-12'),
  cityModal('Mandya'.tr, 'KA-11'),
  cityModal('Mangaluru'.tr, 'KA-19'),
  cityModal('Marathahalli'.tr, 'KA-61'),
  cityModal('Mysuru'.tr, 'KA-09'),
  cityModal('Nagamangala'.tr, 'KA-54'),
  cityModal('Nelamangala'.tr, 'KA-52'),
  cityModal('Puttur'.tr, 'KA-21'),
  cityModal('Raichur'.tr, 'KA-36'),
  cityModal('Ramanagara'.tr, 'KA-42'),
  cityModal('Ramdurg'.tr, 'KA-69'),
  cityModal('Ranebennur'.tr, 'KA-68'),
  cityModal('RT Nagara'.tr, 'KA-60'),
  cityModal('Sagar'.tr, 'KA-15'),
  cityModal('Sakleshpura'.tr, 'KA-46'),
  cityModal('Shantinagara'.tr, 'KA-57'),
  cityModal('Shivamogga'.tr, 'KA-14'),
  cityModal('Sirsi'.tr, 'KA-31'),
  cityModal('Surathkal'.tr, 'KA-62'),
  cityModal('Tarikere'.tr, 'KA-66'),
  cityModal('Tiptur'.tr, 'KA-44'),
  cityModal('Tumakuru'.tr, 'KA-06'),
  cityModal('Udupi'.tr, 'KA-20'),
  cityModal('Vijayapura'.tr, 'KA-28'),
  cityModal('Yadagiri'.tr, 'KA-33'),
  cityModal('Yelahanka'.tr, 'KA-50'),
];

//kerala
List klCities = [
  cityModal('Adoor'.tr, 'KL-26'),
  cityModal('Alappuzha'.tr, 'KL-04'),
  cityModal('Alathur'.tr, 'KL-49'),
  cityModal('Aluva'.tr, 'KL-41'),
  cityModal('Angamaly'.tr, 'KL-63'),
  cityModal('Attingal'.tr, 'KL-16'),
  cityModal('Batheri'.tr, 'KL-73'),
  cityModal('Chadayamangalam'.tr, 'KL-82'),
  cityModal('Chalakkudy'.tr, 'KL-64'),
  cityModal('Changanassery'.tr, 'KL-33'),
  cityModal('Chengannur'.tr, 'KL-30'),
  cityModal('Cherthala'.tr, 'KL-32'),
  cityModal('Chittur'.tr, 'KL-70'),
  cityModal('Guruvayur'.tr, 'KL-46'),
  cityModal('Hosdurg'.tr, 'KL-60'),
  cityModal('Idukki township'.tr, 'KL-06'),
  cityModal('Irinjalakuda'.tr, 'KL-45'),
  cityModal('Iritty'.tr, 'KL-78'),
  cityModal('Kanjirapalli'.tr, 'KL-34'),
  cityModal('Kannur'.tr, 'KL-13'),
  cityModal('Karunagapalli'.tr, 'KL-23'),
  cityModal('Kasaragod'.tr, 'KL-14'),
  cityModal('Kattakada'.tr, 'KL-74'),
  cityModal('Kayamkulam'.tr, 'KL-29'),
  cityModal('Kazhakoottam'.tr, 'KL-22'),
  cityModal('Kochi'.tr, 'KL-07'),
  cityModal('Kodungallor'.tr, 'KL-47'),
  cityModal('Koduvally'.tr, 'KL-57'),
  cityModal('Kollam'.tr, 'KL-02'),
  cityModal('Kondotty'.tr, 'KL-84'),
  cityModal('Konni'.tr, 'KL-83'),
  cityModal('Kothamangalam'.tr, 'KL-44'),
  cityModal('Kottarakara'.tr, 'KL-24'),
  cityModal('Kottayam'.tr, 'KL-05'),
  cityModal('Koyilandy'.tr, 'KL-56'),
  cityModal('Kozhikode'.tr, 'KL-11'),
  cityModal('Kuttanad'.tr, 'KL-66'),
  cityModal('Malappuram'.tr, 'KL-10'),
  cityModal('Mallappally'.tr, 'KL-28'),
  cityModal('Mananthawadi'.tr, 'KL-72'),
  cityModal('Mannarkkad'.tr, 'KL-50'),
  cityModal('Mavelikkara'.tr, 'KL-31'),
  cityModal('Muvattupuzha'.tr, 'KL-17'),
  cityModal('Nanminda'.tr, 'KL-76'),
  cityModal('Nedumangad'.tr, 'KL-21'),
  cityModal('Neyyathinkara'.tr, 'KL-20'),
  cityModal('Nilambur'.tr, 'KL-71'),
  cityModal('Ottapalam'.tr, 'KL-51'),
  cityModal('Palai'.tr, 'KL-35'),
  cityModal('Palakkad'.tr, 'KL-09'),
  cityModal('Parassala'.tr, 'KL-19'),
  cityModal('Parur'.tr, 'KL-42'),
  cityModal('Pathanamthitta'.tr, 'KL-03'),
  cityModal('Pathanapuram'.tr, 'KL-80'),
  cityModal('Pattambi'.tr, 'KL-52'),
  cityModal('Payyannur'.tr, 'KL-86'),
  cityModal('Perambra'.tr, 'KL-77'),
  cityModal('Perinthalmanna'.tr, 'KL-53'),
  cityModal('Perumbavoor'.tr, 'KL-40'),
  cityModal('Ponnani'.tr, 'KL-54'),
  cityModal('Punalur'.tr, 'KL-25'),
  cityModal('Ramanattukara'.tr, 'KL-85'),
  cityModal('Ranni'.tr, 'KL-62'),
  cityModal('Sasthamkotta'.tr, 'KL-61'),
  cityModal('Taliparamba'.tr, 'KL-59'),
  cityModal('Thalassery'.tr, 'KL-58'),
  cityModal('Thiruvananthapuram'.tr, 'KL-01'),
  cityModal('Thodupuzha'.tr, 'KL-38'),
  cityModal('Thriprayar'.tr, 'KL-75'),
  cityModal('Thripunithura'.tr, 'KL-39'),
  cityModal('Thrissur'.tr, 'KL-08'),
  cityModal('Tirur'.tr, 'KL-55'),
  cityModal('Tirurangadi'.tr, 'KL-65'),
  cityModal('Tiruvalla'.tr, 'KL-27'),
  cityModal('Uzhavur'.tr, 'KL-67'),
  cityModal('Vadakara'.tr, 'KL-18'),
  cityModal('Vaikom'.tr, 'KL-36'),
  cityModal('Varkala'.tr, 'KL-81'),
  cityModal('vellarikundu'.tr, 'KL-79'),
  cityModal('Wadakkancherry'.tr, 'KL-48'),
];

//ladakh
List laCities = [
  cityModal('Kargil'.tr, 'LA-01'),
  cityModal('Leh'.tr, 'LA-02'),
];

//maharashtra
List mhCities = [
  cityModal('Ahmednagar'.tr, 'MH-16'),
  cityModal('Akluj'.tr, 'MH-45'),
  cityModal('Akola'.tr, 'MH-30'),
  cityModal('Alibag'.tr, 'MHXX1'),
  cityModal('Ambajogai'.tr, 'MH-44'),
  cityModal('Amravati'.tr, 'MH-27'),
  cityModal('Aurangabad'.tr, 'MH-20'),
  cityModal('Bandra'.tr, 'MHXX2'),
  cityModal('Baramati'.tr, 'MH-42'),
  cityModal('Beed'.tr, 'MH-23'),
  cityModal('Bhandara'.tr, 'MH-36'),
  cityModal('Borivali'.tr, 'MH-47'),
  cityModal('Buldhana'.tr, 'MH-28'),
  cityModal('Chandrapur'.tr, 'MH-34'),
  cityModal('Dhule'.tr, 'MH-18'),
  cityModal('Gadchiroli'.tr, 'MH-33'),
  cityModal('Gondia'.tr, 'MH-35'),
  cityModal('Hingoli'.tr, 'MH-38'),
  cityModal('Jalgaon'.tr, 'MH-19'),
  cityModal('Jalna'.tr, 'MH-21'),
  cityModal('Kalyan'.tr, 'MH-05'),
  cityModal('Karad'.tr, 'MH-50'),
  cityModal('Kolhapur'.tr, 'MH-09'),
  cityModal('Latur'.tr, 'MH-24'),
  cityModal('Malegaon'.tr, 'MH-41'),
  cityModal('Mumbai'.tr, 'MH-01'),
  cityModal('Nagpur'.tr, 'MH-31'),
  cityModal('Nanded'.tr, 'MH-26'),
  cityModal('Nandurbar'.tr, 'MH-39'),
  cityModal('Nashik'.tr, 'MH-15'),
  cityModal('Navi Mumbai'.tr, 'MH-43'),
  cityModal('Oros'.tr, 'MHXX3'),
  cityModal('Osmanabad'.tr, 'MH-25'),
  cityModal('Palghar'.tr, 'MH-48'),
  cityModal('Parbhani'.tr, 'MH-22'),
  cityModal('Pune'.tr, 'MH-12'),
  cityModal('Ratnagiri'.tr, 'MH-08'),
  cityModal('Sangli'.tr, 'MH-10'),
  cityModal('Satara'.tr, 'MH-11'),
  cityModal('Shrirampur'.tr, 'MH-17'),
  cityModal('Sindhudurg'.tr, 'MH-07'),
  cityModal('Solapur'.tr, 'MH-13'),
  cityModal('Thane'.tr, 'MH-04'),
  cityModal('Wardha'.tr, 'MH-32'),
  cityModal('Washim'.tr, 'MH-37'),
  cityModal('Yavatmal'.tr, 'MH-29'),
];

//meghalaya
List mlCities = [
  cityModal('Ampati'.tr, 'MLXX4'),
  cityModal('Baghmara'.tr, 'MLXX5'),
  cityModal('Jaintia Hills'.tr, 'ML-04'),
  cityModal('Jowai'.tr, 'MLXX1'),
  cityModal('Khliehriat'.tr, 'MLXX6'),
  cityModal('Mawkyrwat'.tr, 'MLXX7'),
  cityModal('Nongpoh'.tr, 'MLXX8'),
  cityModal('Nongstoin'.tr, 'MLXX2'),
  cityModal('Resubelpara'.tr, 'MLXX9'),
  cityModal('Shillong'.tr, 'ML-05'),
  cityModal('Tura'.tr, 'MLXX3'),
  cityModal('West Khasi Hills'.tr, 'ML-06'),
  cityModal('Williamnagar'.tr, 'MLXX10'),
];

//manipur
List mnCities = [
  cityModal('Bishnupur'.tr, 'MN-05'),
  cityModal('Chandel'.tr, 'MNXX1'),
  cityModal('Churachandpur'.tr, 'MN-02'),
  cityModal('Imphal'.tr, 'MN-01'),
  cityModal('Jiribam'.tr, 'MNXX2'),
  cityModal('Kakching'.tr, 'MNXX3'),
  cityModal('Kamjong'.tr, 'MNXX4'),
  cityModal('Kangpokpi'.tr, 'MN-03'),
  cityModal('Noney'.tr, 'MNXX5'),
  cityModal('Pherzawl'.tr, 'MNXX6'),
  cityModal('Porompat'.tr, 'MNXX7'),
  cityModal('Senapati'.tr, 'MNXX8'),
  cityModal('Tamenglong'.tr, 'MNXX9'),
  cityModal('Tengnoupal'.tr, 'MNXX10'),
  cityModal('Thoubal'.tr, 'MN-04'),
  cityModal('Ukhrul'.tr, 'MN-07'),
];

//madhya pradesh
List mpCities = [
  cityModal('Agar'.tr, 'MP-70'),
  cityModal('Alirajpur'.tr, 'MP-69'),
  cityModal('Anuppur'.tr, 'MP-65'),
  cityModal('Ashoknagar'.tr, 'MP-67'),
  cityModal('Balaghat'.tr, 'MP-50'),
  cityModal('Barwani'.tr, 'MP-46'),
  cityModal('Betul'.tr, 'MP-48'),
  cityModal('Bhind'.tr, 'MP-30'),
  cityModal('Bhopal'.tr, 'MP-04'),
  cityModal('Burhanpur'.tr, 'MP-68'),
  cityModal('Chachaura'.tr, 'MP-74'),
  cityModal('Chhatarpur'.tr, 'MP-16'),
  cityModal('Chhindwara'.tr, 'MP-28'),
  cityModal('Damoh'.tr, 'MP-34'),
  cityModal('Datia'.tr, 'MP-32'),
  cityModal('Dewas'.tr, 'MP-41'),
  cityModal('Dhar'.tr, 'MP-11'),
  cityModal('Dindori'.tr, 'MP-52'),
  cityModal('Guna'.tr, 'MP-08'),
  cityModal('Gwalior'.tr, 'MP-07'),
  cityModal('Harda'.tr, 'MP-47'),
  cityModal('Hoshangabad'.tr, 'MP-05'),
  cityModal('Indore'.tr, 'MP-09'),
  cityModal('Jabalpur'.tr, 'MP-20'),
  cityModal('Jhabua'.tr, 'MP-45'),
  cityModal('Katni'.tr, 'MPXX1'),
  cityModal('Khandwa'.tr, 'MP-12'),
  cityModal('Khargone'.tr, 'MP-10'),
  cityModal('Maihar'.tr, 'MP-73'),
  cityModal('Mandla'.tr, 'MP-51'),
  cityModal('Mandsaur'.tr, 'MP-14'),
  cityModal('Morena'.tr, 'MP-06'),
  cityModal('Murwara'.tr, 'MP-21'),
  cityModal('Nagda'.tr, 'MP-72'),
  cityModal('Narsinghpur'.tr, 'MP-49'),
  cityModal('Neemuch'.tr, 'MP-44'),
  cityModal('Niwari'.tr, 'MPXX2'),
  cityModal('Panna'.tr, 'MP-35'),
  cityModal('Raisen'.tr, 'MP-38'),
  cityModal('Rajgarh'.tr, 'MP-39'),
  cityModal('Ratlam'.tr, 'MP-43'),
  cityModal('Rewa'.tr, 'MP-17'),
  cityModal('Sagar'.tr, 'MP-15'),
  cityModal('Satna'.tr, 'MP-19'),
  cityModal('Sehore'.tr, 'MP-37'),
  cityModal('Seoni'.tr, 'MP-22'),
  cityModal('Shahdol'.tr, 'MP-18'),
  cityModal('Shajapur'.tr, 'MP-42'),
  cityModal('Sheopur'.tr, 'MP-31'),
  cityModal('Shivpuri'.tr, 'MP-33'),
  cityModal('Sidhi'.tr, 'MP-53'),
  cityModal('Singrauli'.tr, 'MP-66'),
  cityModal('Tikamgarh'.tr, 'MP-36'),
  cityModal('Ujjain'.tr, 'MP-13'),
  cityModal('Umaria'.tr, 'MP-54'),
  cityModal('Vidisha'.tr, 'MP-40'),
];

//mizoram
List mzCities = [
  cityModal('Aizawl'.tr, 'MZ-01'),
  cityModal('Champhai'.tr, 'MZ-04'),
  cityModal('Kolasib'.tr, 'MZ-05'),
  cityModal('Lawngtlai'.tr, 'MZ-07'),
  cityModal('Lunglei'.tr, 'MZ-02'),
  cityModal('Mamit'.tr, 'MZ-08'),
  cityModal('Saiha'.tr, 'MZ-03'),
  cityModal('Serchhip'.tr, 'MZ-06'),
];

//nagaland
List nlCities = [
  cityModal('Dimapur'.tr, 'NL-07'),
  cityModal('Kiphire'.tr, 'NLXX1'),
  cityModal('Kohima'.tr, 'NL-01'),
  cityModal('Longleng'.tr, 'NLXX2'),
  cityModal('Mokokchung'.tr, 'NL-02'),
  cityModal('Mon'.tr, 'NL-04'),
  cityModal('Noklak'.tr, 'NLXX3'),
  cityModal('Peren'.tr, 'NLXX4'),
  cityModal('Phek'.tr, 'NL-08'),
  cityModal('Tuensang'.tr, 'NL-03'),
  cityModal('Wokha'.tr, 'NL-05'),
  cityModal('Zunheboto'.tr, 'NLXX5'),
];

//orissa
List odCities = [
  cityModal('Angul'.tr, 'OD-19'),
  cityModal('Balasore'.tr, 'OD-01'),
  cityModal('Bargarh'.tr, 'OD-17'),
  cityModal('Baripada'.tr, 'ODXX1'),
  cityModal('Bhadrak'.tr, 'OD-22'),
  cityModal('Bhanjanagar'.tr, 'OD-32'),
  cityModal('Bhawanipatna'.tr, 'ODXX2'),
  cityModal('Bhubaneswar'.tr, 'OD-02'),
  cityModal('Bolangir'.tr, 'OD-03'),
  cityModal('Boudh'.tr, 'OD-27'),
  cityModal('Chandikhol'.tr, 'OD-04'),
  cityModal('Chhatrapur'.tr, 'ODXX3'),
  cityModal('Cuttack'.tr, 'OD-05'),
  cityModal('Debagarh'.tr, 'OD-28'),
  cityModal('Dhenkanal'.tr, 'OD-06'),
  cityModal('Ganjam'.tr, 'OD-07'),
  cityModal('Jagatsinghpur'.tr, 'OD-21'),
  cityModal('Jajpur'.tr, 'OD-34'),
  cityModal('Jharsuguda'.tr, 'OD-23'),
  cityModal('Kalahandi'.tr, 'OD-08'),
  cityModal('Kendrapara'.tr, 'OD-29'),
  cityModal('Keonjhar'.tr, 'OD-09'),
  cityModal('Koraput'.tr, 'OD-10'),
  cityModal('Malkangiri'.tr, 'OD-30'),
  cityModal('Mayurbhanj'.tr, 'OD-11'),
  cityModal('Nabarangpur'.tr, 'OD-24'),
  cityModal('Nayagarh'.tr, 'OD-25'),
  cityModal('Nuapada'.tr, 'OD-26'),
  cityModal('Panikoili'.tr, 'ODXX4'),
  cityModal('Paralakhemundi'.tr, 'ODXX5'),
  cityModal('Phulbani'.tr, 'OD-12'),
  cityModal('Puri'.tr, 'OD-13'),
  cityModal('Rayagada'.tr, 'OD-18'),
  cityModal('Rourkela'.tr, 'OD-14'),
  cityModal('Sambalpur'.tr, 'OD-15'),
  cityModal('Subarnapur'.tr, 'ODXX6'),
  cityModal('Sundergarh'.tr, 'OD-16'),
  cityModal('Talcher'.tr, 'OD-35'),
];

//punjab
List pbCities = [
  cityModal('Abohar'.tr, 'PB-15'),
  cityModal('Ahmedgarh'.tr, 'PB-82'),
  cityModal('Ajnala'.tr, 'PB-14'),
  cityModal('Amloh'.tr, 'PB-48'),
  cityModal('Amritsar'.tr, 'PB-02'),
  cityModal('Anandpur Sahib'.tr, 'PB-16'),
  cityModal('Bagha Purana'.tr, 'PB-69'),
  cityModal('Banga'.tr, 'PB-78'),
  cityModal('Barnala'.tr, 'PB-19'),
  cityModal('Bassi Pathana'.tr, 'PB-52'),
  cityModal('Batala'.tr, 'PB-18'),
  cityModal('Bathinda'.tr, 'PB-03'),
  cityModal('Bhawanigarh'.tr, 'PB-84'),
  cityModal('Bhikhiwind'.tr, 'PB-88'),
  cityModal('Budhlada'.tr, 'PB-50'),
  cityModal('Chamkaur Sahib'.tr, 'PB-71'),
  cityModal('Dasuya'.tr, 'PB-21'),
  cityModal('Dera Baba Nanak'.tr, 'PB-58'),
  cityModal('Dera Bassi'.tr, 'PB-70'),
  cityModal('Dhar Kalan'.tr, 'PB-68'),
  cityModal('Dharamkot'.tr, 'PB-76'),
  cityModal('Dhuri'.tr, 'PB-59'),
  cityModal('Dirba'.tr, 'PB-86'),
  cityModal('Faridkot'.tr, 'PB-04'),
  cityModal('Fatehgarh Sahib'.tr, 'PB-23'),
  cityModal('Fazilka'.tr, 'PB-22'),
  cityModal('Firozpur'.tr, 'PB-05'),
  cityModal('Garhshankar'.tr, 'PB-24'),
  cityModal('Gidderbaha'.tr, 'PB-60'),
  cityModal('Gurdaspur'.tr, 'PB-06'),
  cityModal('Hoshiarpur'.tr, 'PB-07'),
  cityModal('Jagraon'.tr, 'PB-25'),
  cityModal('Jaito'.tr, 'PB-62'),
  cityModal('Jalalabad'.tr, 'PB-61'),
  cityModal('Jalandhar'.tr, 'PB-08'),
  cityModal('Kalanaur'.tr, 'PB-85'),
  cityModal('Kapurthala'.tr, 'PB-09'),
  cityModal('Khadoor Sahib'.tr, 'PB-63'),
  cityModal('Khamanon'.tr, 'PB-49'),
  cityModal('Khanna'.tr, 'PB-26'),
  cityModal('Kharar'.tr, 'PB-27'),
  cityModal('Kotkapura'.tr, 'PB-79'),
  cityModal('Lehragaga'.tr, 'PB-75'),
  cityModal('Ludhiana'.tr, 'PB-10'),
  cityModal('Majitha'.tr, 'PB-81'),
  cityModal('Malerkotla'.tr, 'PB-28'),
  cityModal('Malout'.tr, 'PB-53'),
  cityModal('Mansa'.tr, 'PB-31'),
  cityModal('Maur'.tr, 'PB-80'),
  cityModal('Moga'.tr, 'PB-29'),
  cityModal('Mohali'.tr, 'PB-65'),
  cityModal('Moonak'.tr, 'PB-64'),
  cityModal('Morinda'.tr, 'PB-87'),
  cityModal('Mukerian'.tr, 'PB-54'),
  cityModal('Nabha'.tr, 'PB-34'),
  cityModal('Nakodar'.tr, 'PB-33'),
  cityModal('Nangal'.tr, 'PB-74'),
  cityModal('Nawanshahar'.tr, 'PB-32'),
  cityModal('Nihal Singh Wala'.tr, 'PB-66'),
  cityModal('Pathankot'.tr, 'PB-35'),
  cityModal('Patiala'.tr, 'PB-11'),
  cityModal('Patti'.tr, 'PB-38'),
  cityModal('Pattran'.tr, 'PB-72'),
  cityModal('Phagwara'.tr, 'PB-36'),
  cityModal('Phillaur'.tr, 'PB-37'),
  cityModal('Raikot'.tr, 'PB-56'),
  cityModal('Rajpura'.tr, 'PB-39'),
  cityModal('Rampura Phul'.tr, 'PB-40'),
  cityModal('Rupnagar'.tr, 'PB-12'),
  cityModal('Samana'.tr, 'PB-42'),
  cityModal('Samrala'.tr, 'PB-43'),
  cityModal('Sangrur'.tr, 'PB-13'),
  cityModal('Sardulgarh'.tr, 'PB-51'),
  cityModal('SBS Nagar'.tr, 'PB-20'),
  cityModal('Shahkot'.tr, 'PB-67'),
  cityModal('Sri Muktsar Sahib'.tr, 'PB-30'),
  cityModal('Sultanpur Lodhi'.tr, 'PB-41'),
  cityModal('Sunam'.tr, 'PB-44'),
  cityModal('Talwandi Sabo'.tr, 'PB-45'),
  cityModal('Tappa Mandi'.tr, 'PB-73'),
  cityModal('Tarn Taran Sahib'.tr, 'PB-46'),
  cityModal('Zira'.tr, 'PB-47'),
];

//puducherry
List pyCities = [
  cityModal('Karaikal'.tr, 'PY-02'),
  cityModal('Mahe'.tr, 'PY-03'),
  cityModal('Oulgaret'.tr, 'PY-05'),
  cityModal('Puducherry'.tr, 'PY-01'),
  cityModal('Yanam'.tr, 'PY-04'),
];

//rajasthan
List rjCities = [
  cityModal('Abu Road'.tr, 'RJ-38'),
  cityModal('Ajmer'.tr, 'RJ-01'),
  cityModal('Alwar'.tr, 'RJ-02'),
  cityModal('Banswara'.tr, 'RJ-03'),
  cityModal('Baran'.tr, 'RJ-28'),
  cityModal('Barmer'.tr, 'RJ-04'),
  cityModal('Beawar'.tr, 'RJ-36'),
  cityModal('Bharatpur'.tr, 'RJ-05'),
  cityModal('Bhilwara'.tr, 'RJ-06'),
  cityModal('Bhiwadi'.tr, 'RJ-40'),
  cityModal('Bikaner'.tr, 'RJ-07'),
  cityModal('Bundi'.tr, 'RJ-08'),
  cityModal('Chittaurgarh'.tr, 'RJ-09'),
  cityModal('Churu'.tr, 'RJ-10'),
  cityModal('Dausa'.tr, 'RJ-29'),
  cityModal('Dholpur'.tr, 'RJ-11'),
  cityModal('Didwana'.tr, 'RJ-37'),
  cityModal('Dudu'.tr, 'RJ-47'),
  cityModal('Dungarpur'.tr, 'RJ-12'),
  cityModal('Hanumangarh'.tr, 'RJ-31'),
  cityModal('Jaipur'.tr, 'RJ-14'),
  cityModal('Jaisalmer'.tr, 'RJ-15'),
  cityModal('Jhalawar'.tr, 'RJ-17'),
  cityModal('Jhunjhunu'.tr, 'RJ-18'),
  cityModal('Jodhpur'.tr, 'RJ-19'),
  cityModal('Karauli'.tr, 'RJ-34'),
  cityModal('Kekri'.tr, 'RJ-48'),
  cityModal('Kishangarh'.tr, 'RJ-42'),
  cityModal('Kota'.tr, 'RJ-20'),
  cityModal('Kotputli'.tr, 'RJ-32'),
  cityModal('Nagaur'.tr, 'RJ-21'),
  cityModal('Nohar'.tr, 'RJ-49'),
  cityModal('Pali'.tr, 'RJ-22'),
  cityModal('Phalodi'.tr, 'RJ-43'),
  cityModal('Pokhran'.tr, 'RJ-55'),
  cityModal('Pratapgarh'.tr, 'RJ-35'),
  cityModal('Rajsamand'.tr, 'RJ-30'),
  cityModal('Ramganj Mandi'.tr, 'RJ-33'),
  cityModal('Sadulshahar'.tr, 'RJ-56'),
  cityModal('Sawai Madhopur'.tr, 'RJ-25'),
  cityModal('Shahpura'.tr, 'RJ-51'),
  cityModal('Sikar'.tr, 'RJ-23'),
  cityModal('Sirohi'.tr, 'RJ-24'),
  cityModal('Sri Ganganagar'.tr, 'RJ-13'),
  cityModal('Sujangarh'.tr, 'RJ-44'),
  cityModal('Sumerpur'.tr, 'RJ-57'),
  cityModal('Tonk'.tr, 'RJ-26'),
  cityModal('Udaipur'.tr, 'RJ-27'),
];

//sikkim
List skCities = [
  cityModal('Gangtok'.tr, 'SK-01'),
  cityModal('Gyalshing'.tr, 'SK-02'),
  cityModal('Jorethang'.tr, 'SK-04'),
  cityModal('Mangan'.tr, 'SK-03'),
  cityModal('Namchi'.tr, 'SKXX1'),
];

//tamil nadu
List tnCities = [
  cityModal('Ambasamudram'.tr, 'TN-76V'),
  cityModal('Ambattur'.tr, 'TN-13'),
  cityModal('Ambur'.tr, 'TN-83Y'),
  cityModal('Arakkonam'.tr, 'TN-73Z'),
  cityModal('Arani'.tr, 'TN-97'),
  cityModal('Aranthangi'.tr, 'TN-55Z'),
  cityModal('Aravakurichi'.tr, 'TN-47Y'),
  cityModal('Ariyalur'.tr, 'TN-61'),
  cityModal('Aruppukottai'.tr, 'TN-67W'),
  cityModal('Attur'.tr, 'TN-77'),
  cityModal('Avinashi'.tr, 'TN-39Z'),
  cityModal('Batlagundu'.tr, 'TN-57W'),
  cityModal('Bhavani'.tr, 'TN-36W'),
  cityModal('Chengalpattu'.tr, 'TN-19'),
  cityModal('Chennai'.tr, 'TN-01'),
  cityModal('Cheyyar'.tr, 'TN-97Z'),
  cityModal('Chidambaram'.tr, 'TN-91'),
  cityModal('Coimbatore'.tr, 'TN-37'),
  cityModal('Cuddalore'.tr, 'TN-31'),
  cityModal('Dharapuram'.tr, 'TN-78'),
  cityModal('Dharmapuri'.tr, 'TN-29'),
  cityModal('Dindigul'.tr, 'TN-57'),
  cityModal('Erode'.tr, 'TN-33'),
  cityModal('Gingee'.tr, 'TN-16Z'),
  cityModal('Gobichettipalayam'.tr, 'TN-36'),
  cityModal('Gudalur'.tr, 'TN-43Z'),
  cityModal('Gudiyatham'.tr, 'TN-23T'),
  cityModal('Gummidipoondi'.tr, 'TN-18Y'),
  cityModal('Harur'.tr, 'TN-29Z'),
  cityModal('Hosur'.tr, 'TN-70'),
  cityModal('Illuppur'.tr, 'TN-55Y'),
  cityModal('Kallakurichi'.tr, 'TN-15M'),
  cityModal('Kanchipuram'.tr, 'TN-21'),
  cityModal('Kangayam'.tr, 'TN-42Y'),
  cityModal('Karaikudi'.tr, 'TN-63Z'),
  cityModal('Karur'.tr, 'TN-47'),
  cityModal('Kovilpatti'.tr, 'TN-96'),
  cityModal('Krishnagiri'.tr, 'TN-24'),
  cityModal('Kulithalai'.tr, 'TN-47Z'),
  cityModal('Kumarapalayam'.tr, 'TN-34Z'),
  cityModal('Kumbakonam'.tr, 'TN-68'),
  cityModal('Kundrathur'.tr, 'TN-85'),
  cityModal('Lalgudi'.tr, 'TN-48X'),
  cityModal('Madurai'.tr, 'TN-58'),
  cityModal('Madurantakam'.tr, 'TN-19Z'),
  cityModal('Manapparai'.tr, 'TN-45Z'),
  cityModal('Manmangalam'.tr, 'TN-47X'),
  cityModal('Mannargudi'.tr, 'TN-50Z'),
  cityModal('Marthandam'.tr, 'TN-75'),
  cityModal('Mayiladuthurai'.tr, 'TN-82'),
  cityModal('Meenambakkam'.tr, 'TN-22'),
  cityModal('Melur'.tr, 'TN-59Z'),
  cityModal('Mettupalayam'.tr, 'TN-40'),
  cityModal('Mettur'.tr, 'TN-93'),
  cityModal('Musiri'.tr, 'TN-48Y'),
  cityModal('Nagapattinam'.tr, 'TN-51'),
  cityModal('Nagercoil'.tr, 'TN-74'),
  cityModal('Namakkal'.tr, 'TN-28'),
  cityModal('Neyveli'.tr, 'TN-91Y'),
  cityModal('Oddanchatram'.tr, 'TN-94Z'),
  cityModal('Omalur'.tr, 'TN-30W'),
  cityModal('Ooty'.tr, 'TN-43'),
  cityModal('Palacode'.tr, 'TN-29W'),
  cityModal('Palani'.tr, 'TN-94'),
  cityModal('Panruti'.tr, 'TN-31Z'),
  cityModal('Paramakudi'.tr, 'TN-65Z'),
  cityModal('Paramathi Velur'.tr, 'TN-88Z'),
  cityModal('Pattukottai'.tr, 'TN-49Y'),
  cityModal('Perambalur'.tr, 'TN-46'),
  cityModal('Perundurai'.tr, 'TN-56'),
  cityModal('Pollachi'.tr, 'TN-41'),
  cityModal('Poonamallee'.tr, 'TN-12'),
  cityModal('Pudukottai'.tr, 'TN-55'),
  cityModal('Ramanathapuram'.tr, 'TN-65'),
  cityModal('Ranipet'.tr, 'TN-73'),
  cityModal('Rasipuram'.tr, 'TN-28Z'),
  cityModal('Red Hills'.tr, 'TN-18'),
  cityModal('Salem'.tr, 'TN-27'),
  cityModal('Sankagiri'.tr, 'TN-52'),
  cityModal('Sankarankovil'.tr, 'TN-79'),
  cityModal('Sathyamangalam'.tr, 'TN-36Z'),
  cityModal('Sholinganallur'.tr, 'TN-14'),
  cityModal('Sirkazhi'.tr, 'TN-82Z'),
  cityModal('Sivaganga'.tr, 'TN-63'),
  cityModal('Sivakasi'.tr, 'TN-95'),
  cityModal('Sriperumbudur'.tr, 'TN-87'),
  cityModal('Srirangam'.tr, 'TN-48'),
  cityModal('Srivilliputhur'.tr, 'TN-84'),
  cityModal('Sulur'.tr, 'TN-37Z'),
  cityModal('Tambaram'.tr, 'TN-11'),
  cityModal('Tenkasi'.tr, 'TN-76'),
  cityModal('Thanjavur'.tr, 'TN-49'),
  cityModal('Theni'.tr, 'TN-60'),
  cityModal('Thiruchendur'.tr, 'TN-92'),
  cityModal('Thirumangalam'.tr, 'TN-58Z'),
  cityModal('Thirupattur'.tr, 'TN-83M'),
  cityModal('Thiruthani'.tr, 'TN-20X'),
  cityModal('Thiruthuraipoondi'.tr, 'TN-50Y'),
  cityModal('Thiruvannamalai'.tr, 'TN-25'),
  cityModal('Thiruverumbur'.tr, 'TN-81Z'),
  cityModal('Thoothukudi'.tr, 'TN-69'),
  cityModal('Thuraiyur'.tr, 'TN-48Z'),
  cityModal('Tindivanam'.tr, 'TN-16'),
  cityModal('Tiruchengode'.tr, 'TN-34'),
  cityModal('Tiruchirapalli'.tr, 'TN-45'),
  cityModal('Tirunelveli'.tr, 'TN-72'),
  cityModal('Tirupur'.tr, 'TN-39'),
  cityModal('Tiruvallur'.tr, 'TN-20'),
  cityModal('Tiruvarur'.tr, 'TN-50'),
  cityModal('Udumalpet'.tr, 'TN-78Z'),
  cityModal('Ulundurpet'.tr, 'TN-15'),
  cityModal('Usilampatti'.tr, 'TN-58Y'),
  cityModal('Uthamapalayam'.tr, 'TN-60Z'),
  cityModal('Vadipatti'.tr, 'TN-59V'),
  cityModal('Valliyur'.tr, 'TN-72V'),
  cityModal('Valparai'.tr, 'TN-41W'),
  cityModal('Vaniyambadi'.tr, 'TN-83'),
  cityModal('Vazhapadi'.tr, 'TN-77Z'),
  cityModal('Vedasandur'.tr, 'TN-57V'),
  cityModal('Vellore'.tr, 'TN-23'),
  cityModal('Villupuram'.tr, 'TN-32'),
  cityModal('Virudhachalam'.tr, 'TN-91Z'),
  cityModal('Virudhunagar'.tr, 'TN-67'),
];

//tripura
List trCities = [
  cityModal('Agartala'.tr, 'TR-01'),
  cityModal('Ambassa'.tr, 'TR-04'),
  cityModal('Belonia'.tr, 'TRXX1'),
  cityModal('Bishramganj'.tr, 'TRXX2'),
  cityModal('Dharmanagar'.tr, 'TR-05'),
  cityModal('Kailasahar'.tr, 'TR-02'),
  cityModal('Khowai'.tr, 'TR-06'),
  cityModal('Santirbazar'.tr, 'TR-08'),
  cityModal('Sepahijala'.tr, 'TR-07'),
  cityModal('Udaipur'.tr, 'TR-03'),
];

//telangana
List tsCities = [
  cityModal('Adilabad'.tr, 'TS-01'),
  cityModal('Asifabad'.tr, 'TS-20'),
  cityModal('Attapur'.tr, 'TS-07'),
  cityModal('Bhongir'.tr, 'TS-30'),
  cityModal('Bhupalpalle'.tr, 'TS-25'),
  cityModal('Gadwal'.tr, 'TS-33'),
  cityModal('Geesugonda'.tr, 'TSXX1'),
  cityModal('Hyderabad'.tr, 'TS-14'),
  cityModal('Jagtial'.tr, 'TS-21'),
  cityModal('Jangaon'.tr, 'TS-27'),
  cityModal('Kamareddy'.tr, 'TS-17'),
  cityModal('Karimnagar'.tr, 'TS-02'),
  cityModal('Khairtabad  '.tr, 'TS-09'),
  cityModal('Khammam'.tr, 'TS-04'),
  cityModal('Kishanbagh  '.tr, 'TS-12'),
  cityModal('Komaram Bheem'.tr, 'TSXX2'),
  cityModal('Kothagudem'.tr, 'TS-28'),
  cityModal('Mahabubabad'.tr, 'TS-26'),
  cityModal('Mahbubnagar'.tr, 'TS-06'),
  cityModal('Malakpet  '.tr, 'TS-11'),
  cityModal('Mancherial'.tr, 'TS-19'),
  cityModal('Medak'.tr, 'TS-35'),
  cityModal('Medchal'.tr, 'TS-08'),
  cityModal('Mulugu'.tr, 'TS-37'),
  cityModal('Nagarkurnool'.tr, 'TS-31'),
  cityModal('Nalgonda'.tr, 'TS-05'),
  cityModal('Narayanpet'.tr, 'TS-38'),
  cityModal('Nirmal'.tr, 'TS-18'),
  cityModal('Nizamabad'.tr, 'TS-16'),
  cityModal('Peddapalli'.tr, 'TS-22'),
  cityModal('Sangareddy'.tr, 'TS-15'),
  cityModal('Secunderabad  '.tr, 'TS-10'),
  cityModal('Shamirpet'.tr, 'TSXX3'),
  cityModal('Shamshabad'.tr, 'TSXX4'),
  cityModal('Siddipet'.tr, 'TS-36'),
  cityModal('Sircilla'.tr, 'TS-23'),
  cityModal('Suryapet'.tr, 'TS-29'),
  cityModal('Tolichowki  '.tr, 'TS-13'),
  cityModal('Vikarabad'.tr, 'TS-34'),
  cityModal('Wanaparthy'.tr, 'TS-32'),
  cityModal('Warangal'.tr, 'TS-03'),
];

//uttrakhand
List ukCities = [
  cityModal('Almora'.tr, 'UK-01'),
  cityModal('Bageshwar'.tr, 'UK-02'),
  cityModal('Champawat'.tr, 'UK-03'),
  cityModal('Dehradun'.tr, 'UK-07'),
  cityModal('Gopeshwar'.tr, 'UK-11'),
  cityModal('Haldwani'.tr, 'UK-04'),
  cityModal('Haridwar'.tr, 'UK-08'),
  cityModal('Kashipur'.tr, 'UK-18'),
  cityModal('Kotdwar'.tr, 'UK-15'),
  cityModal('Nainital'.tr, 'self01'),
  cityModal('Pauri'.tr, 'UK-12'),
  cityModal('Pithoragarh'.tr, 'UK-05'),
  cityModal('Ramnagar'.tr, 'UK-19'),
  cityModal('Ranikhet'.tr, 'UK-20'),
  cityModal('Rishikesh'.tr, 'UK-14'),
  cityModal('Roorkee'.tr, 'UK-17'),
  cityModal('Rudraprayag'.tr, 'UK-13'),
  cityModal('Rudrapur'.tr, 'UK-06'),
  cityModal('Tehri'.tr, 'UK-09'),
  cityModal('Uttarkashi'.tr, 'UK-10'),
  cityModal('Vikasnagar'.tr, 'UK-16'),
];

//uttar pradesh
List upCities = [
  cityModal('Agra'.tr, 'UP-80'),
  cityModal('Aligarh'.tr, 'UP-81'),
  cityModal('Allahabad'.tr, 'UPXX1'),
  cityModal('Ambedkar Nagar'.tr, 'UP-45'),
  cityModal('Amethi'.tr, 'UP-36'),
  cityModal('Amroha'.tr, 'UP-23'),
  cityModal('Auraiya'.tr, 'UP-79'),
  cityModal('Ayodhya'.tr, 'UP-42'),
  cityModal('Azamgarh'.tr, 'UP-50'),
  cityModal('Badaun'.tr, 'UP-24'),
  cityModal('Baghpat'.tr, 'UP-17'),
  cityModal('Bahraich'.tr, 'UP-40'),
  cityModal('Ballia'.tr, 'UP-60'),
  cityModal('Balrampur'.tr, 'UP-47'),
  cityModal('Banda'.tr, 'UP-90'),
  cityModal('Barabanki'.tr, 'UP-41'),
  cityModal('Bareilly'.tr, 'UP-25'),
  cityModal('Basti'.tr, 'UP-51'),
  cityModal('Bhadohi'.tr, 'UP-66'),
  cityModal('Bijnor'.tr, 'UP-20'),
  cityModal('Bulandshahar'.tr, 'UP-13'),
  cityModal('Chandauli'.tr, 'UP-67'),
  cityModal('Chitrakoot'.tr, 'UP-96'),
  cityModal('Deoria'.tr, 'UP-52'),
  cityModal('Etah'.tr, 'UP-82'),
  cityModal('Etawah'.tr, 'UP-75'),
  cityModal('Faizabad'.tr, 'UPXX2'),
  cityModal('Farrukhabad'.tr, 'UP-76'),
  cityModal('Fatehgarh'.tr, 'UPXX3'),
  cityModal('Fatehpur'.tr, 'UP-71'),
  cityModal('Firozabad'.tr, 'UP-83'),
  cityModal('Gauriganj'.tr, 'UPXX4'),
  cityModal('Gautam Buddh Nagar'.tr, 'UP-16'),
  cityModal('Ghaziabad'.tr, 'UP-14'),
  cityModal('Ghazipur'.tr, 'UP-61'),
  cityModal('Gonda'.tr, 'UP-43'),
  cityModal('Gorakhpur'.tr, 'UP-53'),
  cityModal('Gyanpur'.tr, 'UPXX5'),
  cityModal('Hamirpur'.tr, 'UP-91'),
  cityModal('Hapur'.tr, 'UP-37'),
  cityModal('Hardoi'.tr, 'UP-30'),
  cityModal('Hathras'.tr, 'UP-86'),
  cityModal('Jalaun'.tr, 'UP-92'),
  cityModal('Jaunpur'.tr, 'UP-62'),
  cityModal('Jhansi'.tr, 'UP-93'),
  cityModal('Kannauj'.tr, 'UP-74'),
  cityModal('Kanpur Dehat'.tr, 'UP-77'),
  cityModal('Kanpur Nagar'.tr, 'UP-78'),
  cityModal('Karwi'.tr, 'UPXX6'),
  cityModal('Kasganj'.tr, 'UP-87'),
  cityModal('Kaushambi'.tr, 'UP-73'),
  cityModal('Khalilabad'.tr, 'UPXX7'),
  cityModal('Kushinagar'.tr, 'UP-57'),
  cityModal('Lakhimpur Kheri'.tr, 'UP-31'),
  cityModal('Lalitpur'.tr, 'UP-94'),
  cityModal('Lucknow'.tr, 'UP-32'),
  cityModal('Maharajganj'.tr, 'UP-56'),
  cityModal('Mahoba'.tr, 'UP-95'),
  cityModal('Mainpuri'.tr, 'UP-84'),
  cityModal('Manjhanpur'.tr, 'UPXX8'),
  cityModal('Mathura'.tr, 'UP-85'),
  cityModal('Mau'.tr, 'UP-54'),
  cityModal('Meerut'.tr, 'UP-15'),
  cityModal('Mirzapur'.tr, 'UP-63'),
  cityModal('Moradabad'.tr, 'UP-21'),
  cityModal('Muzaffarnagar'.tr, 'UP-12'),
  cityModal('Naugarh'.tr, 'UPXX9'),
  cityModal('Noida'.tr, 'UPXX10'),
  cityModal('Orai'.tr, 'UPXX11'),
  cityModal('Padrauna'.tr, 'UPXX12'),
  cityModal('Pilibhit'.tr, 'UP-26'),
  cityModal('Pratapgarh'.tr, 'UP-72'),
  cityModal('Prayagraj'.tr, 'UP-70'),
  cityModal('Raebareli'.tr, 'UP-33'),
  cityModal('Rampur'.tr, 'UP-22'),
  cityModal('Robertsganj'.tr, 'UPXX13'),
  cityModal('Saharanpur'.tr, 'UP-11'),
  cityModal('Sambhal'.tr, 'UP-38'),
  cityModal('Sant Kabir Nagar'.tr, 'UP-58'),
  cityModal('Shahjahanpur'.tr, 'UP-27'),
  cityModal('Shamli'.tr, 'UP-19'),
  cityModal('Shravasti'.tr, 'UP-46'),
  cityModal('Siddharth Nagar'.tr, 'UP-55'),
  cityModal('Sitapur'.tr, 'UP-34'),
  cityModal('Sonbhadra'.tr, 'UP-64'),
  cityModal('Sultanpur'.tr, 'UP-44'),
  cityModal('Unnao'.tr, 'UP-35'),
  cityModal('Varanasi'.tr, 'UP-65'),
];

//west bengal
List wbCities = [
  cityModal('Alipore'.tr, 'WB-20'),
  cityModal('Alipurduar'.tr, 'WB-70'),
  cityModal('Asansol'.tr, 'WB-38'),
  cityModal('Baharampur'.tr, 'WBXX1'),
  cityModal('Balurghat'.tr, 'WB-62'),
  cityModal('Bangaon'.tr, 'WB-28'),
  cityModal('Bankura'.tr, 'WB-68'),
  cityModal('Barasat'.tr, 'WB-26'),
  cityModal('Barrackpore'.tr, 'WB-24'),
  cityModal('Baruipur'.tr, 'WB-96'),
  cityModal('Behala'.tr, 'WB-10'),
  cityModal('Beltala'.tr, 'WB-04'),
  cityModal('Birbhum'.tr, 'WB-54'),
  cityModal('Bolpur'.tr, 'WB-48'),
  cityModal('Burdwan'.tr, 'WB-42'),
  cityModal('Chanchal'.tr, 'WB-84'),
  cityModal('Chinsurah'.tr, 'WB-16'),
  cityModal('Contai'.tr, 'WB-32'),
  cityModal('Cooch Behar'.tr, 'WB-64'),
  cityModal('Darjeeling'.tr, 'WB-77'),
  cityModal('Diamond Harbour'.tr, 'WB-98'),
  cityModal('Durgapur'.tr, 'WB-40'),
  cityModal('Howrah'.tr, 'WB-12'),
  cityModal('Islampur'.tr, 'WB-92'),
  cityModal('Jalpaiguri'.tr, 'WB-72'),
  cityModal('Jaynagar'.tr, 'WB-99'),
  cityModal('Jhargram'.tr, 'WB-50'),
  cityModal('Kalimpong'.tr, 'WB-79'),
  cityModal('Kalna'.tr, 'WB-44'),
  cityModal('Kalyani'.tr, 'WB-90'),
  cityModal('Kasba'.tr, 'WB-06'),
  cityModal('Kharagpur'.tr, 'WB-36'),
  cityModal('Kolkata'.tr, 'WBXX2'),
  cityModal('Krishnanagar'.tr, 'WB-52'),
  cityModal('Malda'.tr, 'WB-66'),
  cityModal('Mathabhanga'.tr, 'WB-86'),
  cityModal('Medinipur'.tr, 'WB-34'),
  cityModal('Murshidabad'.tr, 'WB-58'),
  cityModal('Purulia'.tr, 'WB-56'),
  cityModal('Raghunathpur'.tr, 'WB-82'),
  cityModal('Raiganj'.tr, 'WB-60'),
  cityModal('Rampurhat'.tr, 'WB-46'),
  cityModal('Serampore'.tr, 'WB-18'),
  cityModal('Siliguri'.tr, 'WB-74'),
  cityModal('Suri'.tr, 'WBXX3'),
  cityModal('Tamluk'.tr, 'WB-30'),
  cityModal('Uluberia'.tr, 'WB-14'),
];
